language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_786137cd8cc5_key -iv $encrypted_786137cd8cc5_iv
  -in github_deploy.enc -out github_deploy -d
script: npm run deploy
